//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMS.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 #jet
        ///0	0	144
        ///0	0	160
        ///0	0	176
        ///0	0	192
        ///0	0	208
        ///0	0	224
        ///0	0	240
        ///0	0	255
        ///0	16	255
        ///0	32	255
        ///0	48	255
        ///0	64	255
        ///0	80	255
        ///0	96	255
        ///0	112	255
        ///0	128	255
        ///0	144	255
        ///0	160	255
        ///0	176	255
        ///0	192	255
        ///0	208	255
        ///0	224	255
        ///0	240	255
        ///0	255	255
        ///16	255	240
        ///32	255	224
        ///48	255	208
        ///64	255	192
        ///80	255	176
        ///96	255	160
        ///112	255	144
        ///128	255	128
        ///144	255	112
        ///160	255	96
        ///176	255	80
        ///192	255	64
        ///208	255	48
        ///224	255	32
        ///240	255	16
        ///255	255	0
        ///255	240	0
        ///255	224	0
        ///255	208	0
        ///255	192	0
        ///255	176	0
        ///255	160	0
        ///255	 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ColorBar {
            get {
                return ResourceManager.GetString("ColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_add_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 窗口图标_32 {
            get {
                object obj = ResourceManager.GetObject("窗口图标_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 菜单按钮F {
            get {
                object obj = ResourceManager.GetObject("菜单按钮F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 菜单按钮T {
            get {
                object obj = ResourceManager.GetObject("菜单按钮T", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
